[colors-dark]
# Fundo preto sólido simples sem transparência (economia de recursos)
alpha=1.0
background=000000
foreground=f1dfdc

# Cursor
cursor=1a1110 ffb4a8

# Normal (0-7)
regular0=271d1c
regular1=ffb4ab
regular2=8bd88e
regular3=dfc26e
regular4=ffb4a8
regular5=dec48c
regular6=80d5d2
regular7=d8c2be

# Bright (8-15)
bright0=534341
bright1=ffb4ab
bright2=a6e3a1
bright3=f9e2af
bright4=ffb4a8
bright5=f8d8fe
bright6=94e2d5
bright7=f1dfdc

# URLs
urls=ffb4a8

# Seleção
selection-foreground=f1dfdc
selection-background=73342b
