[colors-dark]
# Fundo preto sólido simples sem transparência (economia de recursos)
alpha=1.0
background=000000
foreground=e4e1e9

# Cursor
cursor=131318 bdc2ff

# Normal (0-7)
regular0=1f1f25
regular1=ffb4ab
regular2=8bd88e
regular3=dfc26e
regular4=bdc2ff
regular5=e7b9d6
regular6=80d5d2
regular7=c7c5d0

# Bright (8-15)
bright0=46464f
bright1=ffb4ab
bright2=a6e3a1
bright3=f9e2af
bright4=bdc2ff
bright5=f8d8fe
bright6=94e2d5
bright7=e4e1e9

# URLs
urls=bdc2ff

# Seleção
selection-foreground=e4e1e9
selection-background=3c4279
