[colors-dark]
# Gerado nativamente via Matugen templates
alpha=0.0
background=111318
foreground=e2e2e9

# Cursor
cursor=111318 a9c7ff

# Normal (0-7)
regular0=1d2024
regular1=ffb4ab
regular2=8bd88e
regular3=dfc26e
regular4=a9c7ff
regular5=dcbce1
regular6=80d5d2
regular7=c4c6d0

# Bright (8-15)
bright0=44474e
bright1=ffb4ab
bright2=a6e3a1
bright3=f9e2af
bright4=a9c7ff
bright5=f8d8fe
bright6=94e2d5
bright7=e2e2e9

# URLs
urls=a9c7ff

# Seleção
selection-foreground=e2e2e9
selection-background=274777
