preload = /home/gabriel/Pictures/Wallpapers/ocean-wave-scenery-digital-art-4k-wallpaper-uhdpaper.com-158@5@g.jpg
wallpaper = eDP-1,/home/gabriel/Pictures/Wallpapers/ocean-wave-scenery-digital-art-4k-wallpaper-uhdpaper.com-158@5@g.jpg
splash = false
