[colors-dark]
# Fundo preto sólido simples sem transparência (economia de recursos)
alpha=1.0
background=000000
foreground={{colors.on_surface.default.hex | replace: "#", ""}}

# Cursor
cursor={{colors.surface.default.hex | replace: "#", ""}} {{colors.primary.default.hex | replace: "#", ""}}

# Normal (0-7)
regular0={{colors.surface_container.default.hex | replace: "#", ""}}
regular1={{colors.error.default.hex | replace: "#", ""}}
regular2=8bd88e
regular3=dfc26e
regular4={{colors.primary.default.hex | replace: "#", ""}}
regular5={{colors.tertiary.default.hex | replace: "#", ""}}
regular6=80d5d2
regular7={{colors.on_surface_variant.default.hex | replace: "#", ""}}

# Bright (8-15)
bright0={{colors.outline_variant.default.hex | replace: "#", ""}}
bright1={{colors.error.default.hex | replace: "#", ""}}
bright2=a6e3a1
bright3=f9e2af
bright4={{colors.primary.default.hex | replace: "#", ""}}
bright5=f8d8fe
bright6=94e2d5
bright7={{colors.on_surface.default.hex | replace: "#", ""}}

# URLs
urls={{colors.primary.default.hex | replace: "#", ""}}

# Seleção
selection-foreground={{colors.on_surface.default.hex | replace: "#", ""}}
selection-background={{colors.primary_container.default.hex | replace: "#", ""}}
